/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ffm-service_CONSTANTS_H
#define ffm-service_CONSTANTS_H

#include "ffm-service_types.h"



class ffm-serviceConstants {
 public:
  ffm-serviceConstants();

};

extern const ffm-serviceConstants g_ffm-service_constants;



#endif
