/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ffm-service_constants.h"



const ffm-serviceConstants g_ffm-service_constants;

ffm-serviceConstants::ffm-serviceConstants() {
}



