/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ffm_service_constants.h"



const ffm_serviceConstants g_ffm_service_constants;

ffm_serviceConstants::ffm_serviceConstants() {
}



