/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ffm_service_CONSTANTS_H
#define ffm_service_CONSTANTS_H

#include "ffm_service_types.h"



class ffm_serviceConstants {
 public:
  ffm_serviceConstants();

};

extern const ffm_serviceConstants g_ffm_service_constants;



#endif
